"""empty message

Revision ID: 32555b563af4
Revises: 929911a6746e
Create Date: 2021-06-05 22:21:26.562086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32555b563af4'
down_revision = '929911a6746e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.String(length=250), nullable=True))
    op.add_column('artist', sa.Column('looking_venue', sa.Boolean(), nullable=True))
    op.add_column('artist', sa.Column('seeking_desc', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('website_link', sa.String(length=400), nullable=True))
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'genres')
    op.drop_column('venue', 'seeking_talent')
    op.drop_column('venue', 'website_link')
    op.drop_column('artist', 'seeking_desc')
    op.drop_column('artist', 'looking_venue')
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###
