"""empty message

Revision ID: a599b9afcb7b
Revises: 1ec2bc5e9478
Create Date: 2021-06-10 22:56:17.059661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a599b9afcb7b'
down_revision = '1ec2bc5e9478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genres_list', sa.PickleType(), nullable=True))
    op.drop_column('artist', 'genres')
    op.add_column('venue', sa.Column('genres_list', sa.PickleType(), nullable=True))
    op.drop_column('venue', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venue', 'genres_list')
    op.add_column('artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('artist', 'genres_list')
    # ### end Alembic commands ###
